package io.github.edadma.typesetter

case object UNDEFINED {
  override def toString = "undefined"
}

val `LATIN SMALL LIGATURE FF` = "\uFB00"
val `LATIN SMALL LIGATURE FI` = "\uFB01"
val `LATIN SMALL LIGATURE FL` = "\uFB02"
val `LATIN SMALL LIGATURE FFI` = "\uFB03"
val `LATIN SMALL LIGATURE FFL` = "\uFB04"

val `LEFT SINGLE QUOTATION MARK` = "\u2018"
val `RIGHT SINGLE QUOTATION MARK` = "\u2019"
val `LEFT DOUBLE QUOTATION MARK` = "\u201C"
val `RIGHT DOUBLE QUOTATION MARK` = "\u201D"

val HYPHEN = "\u2010"
val `EN DASH` = "\u2013"
val `EM DASH` = "\u2014"

val `LEFTWARDS ARROW` = "\u2190"
val `RIGHTWARDS ARROW` = "\u2192"
val `LEFT RIGHT ARROW` = "\u2194"
val `LEFTWARDS DOUBLE ARROW` = "\u21D0"
val `RIGHTWARDS DOUBLE ARROW` = "\u21D2"
val `LEFT RIGHT DOUBLE ARROW` = "\u21D4"

val `LONG LEFTWARDS ARROW` = "\u27F5"
val `LONG RIGHTWARDS ARROW` = "\u27F6"
val `LONG LEFT RIGHT ARROW` = "\u27F7"
val `LONG LEFTWARDS DOUBLE ARROW` = "\u27F8"
val `LONG RIGHTWARDS DOUBLE ARROW` = "\u27F9"
val `LONG LEFT RIGHT DOUBLE ARROW` = "\u27Fa"

val `HORIZONTAL ELLIPSIS` = "\u2026"
